# Generated by Django 5.0.3 on 2024-04-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='quantité',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='meal',
            new_name='repas',
        ),
    ]
