# Generated by Django 4.1.13 on 2024-04-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_rename_quantity_order_quantité_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='repas',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantité',
            new_name='quantity',
        ),
    ]
