# Generated by Django 4.2.11 on 2024-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_rename_repas_order_meal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='Quantité',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='meal',
            new_name='Repas',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
