# Generated by Django 4.2.11 on 2024-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_rename_quantity_order_quantité_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=216, max_length=15),
        ),
    ]
