# Generated by Django 4.2.11 on 2024-05-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='Numéro_de_téléphone',
        ),
    ]
