# Generated by Django 5.0.3 on 2024-03-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_client_first_name_remove_client_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
