# Generated by Django 5.0.4 on 2024-05-08 15:07

import utils.generate_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=8),
        ),
    ]
