# Generated by Django 5.0.3 on 2024-04-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_persons',
            new_name='nombre_de_personnes',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='temps',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='téléphone',
        ),
    ]
